name: scribble_etome_plugin_plus
description: "Writing sdk for etome tablet"
version: 0.0.8
homepage:

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.leywin.scribble_etome_plugin_plus
        pluginClass: ScribbleEtomePlugin